"""News adding description and image1

Revision ID: e95bfdfba7b3
Revises: 6af655816498
Create Date: 2023-02-04 15:35:56.378661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e95bfdfba7b3'
down_revision = '6af655816498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image1', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_post', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('image1')

    # ### end Alembic commands ###
